blank_issues_enabled: false
contact_links:
  - name: Product, spec & order support
    url: https://www.ltfse.com/contact
    about: For sales, spec or order questions (not code issues), reach the L&T team here.
