import type { Category, Product } from "./types";

/**
 * Real L&T / Panda® catalog, scraped from ekitchensupply.com and pandarange.com.
 * Prices, model numbers, specs and photos are the company's own. Ratings/review
 * counts and badges are illustrative. Photos live under /public/products.
 */

export const CATEGORIES: Category[] = [
  { id: "wok-range", name: "Wok Ranges", art: "range", count: "Signature series", blurb: "Custom-made Panda® wok ranges — jet burners, turbo chambers and smart cooling, built for high-output Oriental cooking." },
  { id: "optispace", name: "Multipurpose Cookers", art: "range", count: "OptiSpace", blurb: "Interchangeable gas cookers and noodle stations — flexible, high-performance cooking zones in a compact footprint." },
  { id: "steamer", name: "Steamers", art: "rice", count: "High-Speed", blurb: "Panda® High-Speed steamer cabinets and steam ranges — dim sum, rice, seafood and more in minutes." },
  { id: "roaster", name: "Roasters & Ovens", art: "oven", count: "Wet-roast", blurb: "Energy-efficient roaster ovens, convection ovens and broilers for Peking duck, char siu and Western roasting." },
  { id: "electric", name: "Electric & Automation", art: "range", count: "Induction + AI", blurb: "Induction wok ranges, auto-lift noodle cookers and intelligent stir-fry machines that cut labor and fuel cost." },
  { id: "electric-kitchen-tool", name: "Small Appliances", art: "wok", count: "Prep power", blurb: "Scallion shredders, slicers, rice cookers and beverage equipment for fast, consistent prep." },
  { id: "refrigeration", name: "Refrigeration", art: "fridge", count: "Reach-in + prep", blurb: "Reach-ins, chef bases, sandwich prep tables and ice machines — R290, ETL-Sanitation certified." },
  { id: "hood", name: "Ventilation & Hoods", art: "lamp", count: "Purification", blurb: "Kitchen ventilation and purification systems and canopy hoods engineered for heavy wok output." },
  { id: "accessories", name: "Accessories", art: "rack", count: "Parts & handling", blurb: "Overshelves, fryer filtration, lockers and material-handling equipment to complete the line." },
  { id: "kitchenware", name: "Kitchenware", art: "wok", count: "Smallwares", blurb: "Steam-table pans, fry pans, ladles and porcelain — NSF-listed commercial smallwares." },
];

const P = (p: Product): Product => p;

export const PRODUCTS: Product[] = [
  // ---------- Wok Ranges ----------
  P({ slug: "52527", sku: "52527", name: "Turbo Wok Range — 1 Burner + 1 Warming Pot", cat: "wok-range", art: "range", price: 12177, images: ["/products/52527-1.png", "/products/52527-2.jpg", "/products/52527-3.jpg", "/products/52527-4.jpg"], brand: "Panda®", rating: 4.9, n: 64, badge: "New", stock: "in", description: "A \"quiet, fierce monster\" turbo jet wok range delivering blast firepower with a high-speed turbo chamber plus a warming pot, ductile-iron chamber ring and smart cooling line.", specs: { "Wok Burners": "1", "Wok Burner BTU": "125,000", "Total BTU": "125,000", "Dimensions": "48\"W × 48\"D × 55\"H", "Weight": "740 lbs", "Gas Type": "Natural / Propane", "Chamber Ring": "Ductile Iron", "Faucet": "California Faucet", "Installation": "Freestanding" } }),
  P({ slug: "58079", sku: "58079", name: "15\" Panda Curved-Steel Chamber Blower Stove — HK Style", cat: "wok-range", art: "range", price: 11970, images: ["/products/58079-1.png"], brand: "Panda®", rating: 4.8, n: 22, stock: "in", description: "Standard 15\" Panda curved-steel bladder chamber with smoke pass, Hong Kong style single-fried single-tail blower stove.", specs: { "Chamber": "15\" curved steel bladder", "Style": "Hong Kong single-fried single-tail", "Feature": "Smoke pass, blower", "Installation": "Freestanding" } }),
  P({ slug: "dchpa48", sku: "DCHPA48", name: "Dukers 48\" Eight-Burner Hot Plate", cat: "wok-range", art: "range", price: 1605, images: ["/products/dchpa48-1.jpg", "/products/dchpa48-2.jpg"], brand: "Dukers", rating: 4.7, n: 138, stock: "in", description: "Countertop gas hotplate, 48\"W, eight stainless burners with cast-iron grates, independent manual controls, full-length seamless drip pan. 256,000 BTU, CSA.", specs: { "Width": "48\"", "Depth": "28¾\"", "Height": "13⅜\"", "Weight": "198 lbs", "Total BTU": "256,000", "Burners": "8", "Gas Type": "Natural / LP", "Certification": "CSA" } }),
  P({ slug: "19029", sku: "19029", name: "Countertop Clay-Pot Range with Pan Burner", cat: "wok-range", art: "range", price: 1617, images: ["/products/19029-1.png", "/products/19029-2.jpg", "/products/19029-3.jpg"], brand: "Panda®", rating: 4.8, n: 41, stock: "in", description: "Compact countertop open range with a 10-jet pan burner and 360° steering faucet — ideal for clay-pot and single-wok service.", specs: { "Width": "19\"", "Depth": "27\"", "Height": "19\"", "Weight": "90 lbs", "Total BTU": "40,000", "Burner": "10-jet", "Faucet": "360° Steering", "Installation": "Countertop" } }),

  // ---------- Multipurpose Cookers (OptiSpace) ----------
  P({ slug: "52740", sku: "52740", name: "16\" Gas Noodle Cooker — Auto Water Fill, 6-Basket", cat: "optispace", art: "range", price: 4563, was: 5952, images: ["/products/52740-1.jpg", "/products/52740-2.jpg", "/products/52740-3.jpg"], brand: "Panda®", rating: 4.9, n: 96, badge: "Sale", stock: "in", description: "OptiSpace 16\" gas noodle cooker with automatic water fill-in and six baskets — U-tube burner, 8-gallon tank, safety-switch gas valve.", specs: { "Width": "16\"", "Depth": "34\"", "Height": "51\"", "Weight": "392 lbs", "Total BTU": "130,000", "Water Capacity": "8 gal", "Baskets": "6", "Burner": "U-Tube", "Installation": "Freestanding" } }),
  P({ slug: "52739", sku: "52739", name: "23\" Gas Noodle Cooker — Auto Water Fill, 9-Basket", cat: "optispace", art: "range", price: 6867, images: ["/products/52739-1.jpg", "/products/52739-2.jpg"], brand: "Panda®", rating: 4.8, n: 47, stock: "in", description: "OptiSpace 23\" gas noodle cooker with automatic water fill-in and nine baskets — high-throughput noodle and dumpling service.", specs: { "Width": "23\"", "Depth": "34\"", "Height": "51\"", "Weight": "464 lbs", "Total BTU": "130,000", "Water Capacity": "10 gal", "Baskets": "9", "Burner": "U-Tube", "Installation": "Freestanding" } }),
  P({ slug: "dcf5-lpg", sku: "DCF5-LPG", name: "Dukers 21\" 70 lb LP Gas Fryer", cat: "optispace", art: "fryer", price: 1623, images: ["/products/dcf5-lpg-1.jpg"], brand: "Dukers", rating: 4.7, n: 210, stock: "in", description: "Floor-model LP fryer, 70 lb capacity, five cast-iron tube burners, millivolt control, twin baskets. 150,000 BTU, CSA.", specs: { "Width": "21\"", "Depth": "32⅞\"", "Height": "45\"", "Weight": "220 lbs", "Total BTU": "150,000", "Capacity": "70 lb", "Gas Type": "LP", "Certification": "CSA" } }),

  // ---------- Steamers ----------
  P({ slug: "52519", sku: "52519", name: "24\" High-Speed Steamer Cabinet", cat: "steamer", art: "rice", price: 13117, images: ["/products/52519-1.png", "/products/52519-2.jpg", "/products/52519-3.jpg"], brand: "Panda®", rating: 4.9, n: 58, badge: "New", stock: "in", description: "Panda® High-Speed steamer cabinet — three independently controlled compartments, torch burners, auto-reload water and flame-failure protection. Steam in seconds.", specs: { "Width": "24\"", "Depth": "36\"", "Height": "77\"", "Weight": "710 lbs", "Total BTU": "90,000", "Water Capacity": "12 gal", "Burner": "Torch", "Compartments": "3", "Installation": "Freestanding" } }),
  P({ slug: "st-1203", sku: "ST-120-3", name: "Adcraft 3-Bay Stainless Steam Table", cat: "steamer", art: "rice", price: 1959, images: ["/products/st-1203-1.jpg"], brand: "Adcraft", rating: 4.6, n: 174, stock: "in", description: "Three 8\"-deep open wells lined with galvanized steel keep hot foods at serving temperature — built for tough kitchen environments.", specs: { "Bays": "3", "Well Depth": "8\"", "Material": "Stainless / galvanized", "Type": "Steam table" } }),
  P({ slug: "sk-r100gs", sku: "SK-R100GS", name: "Sunkyung Gas Rice Steamer Cabinet — 100 Person", cat: "steamer", art: "rice", price: 11111, images: ["/products/sk-r100gs-1.jpg"], brand: "Sunkyung", rating: 4.7, n: 33, stock: "back", description: "Commercial gas rice steamer cabinet for ~100 persons — STS304 body, PCB button control, reservation function, self-diagnosis display.", specs: { "Capacity": "~100 persons", "Body": "STS304 stainless", "Control": "PCB button", "Dimensions": "708 × 706 × 965 mm", "Power": "220V / 60Hz / 35W", "Gas (LNG)": "15,000 kcal/h" } }),

  // ---------- Roasters & Ovens ----------
  P({ slug: "53849", sku: "53849", name: "38\" × 42\" Multipurpose Pork Roaster Oven", cat: "roaster", art: "oven", price: 17952, images: ["/products/53849-1.png"], brand: "Panda®", rating: 4.9, n: 29, stock: "in", description: "Combines Asian and Western technique — wet roasting, smoking and broiling. Three tube burners, 3\" fire-rated insulation, five track levels.", specs: { "Width": "49\"", "Depth": "99\"", "Height": "87\"", "Weight": "2,340 lbs", "Total BTU": "280,000", "Burner": "Tube", "Modes": "Roast / Smoke / Broil", "Installation": "Freestanding" } }),
  P({ slug: "55761", sku: "55761", name: "24\" Gas BBQ Grill", cat: "roaster", art: "oven", price: 1795, images: ["/products/55761-1.png"], brand: "Panda®", rating: 4.6, n: 87, stock: "in", description: "Countertop LP gas BBQ grill with tube burner and brass valve — compact char and finish station.", specs: { "Width": "31\"", "Depth": "12\"", "Height": "11\"", "Weight": "90 lbs", "Total BTU": "20,000", "Gas Type": "Liquid Propane", "Burner": "Tube" } }),
  P({ slug: "dccog1", sku: "DCCOG1", name: "Dukers 38\" Single-Deck Convection Oven", cat: "roaster", art: "oven", price: 5200, images: ["/products/dccog1-1.jpg"], brand: "Dukers", rating: 4.7, n: 152, badge: "Sale", stock: "in", description: "Standard-depth single-deck gas convection oven — even bake and roast, dependable throughput. CSA.", specs: { "Width": "38\"", "Depth": "39¾\"", "Height": "61¾\"", "Weight": "195 lbs", "Gas Type": "Natural / LP", "Certification": "CSA" } }),
  P({ slug: "dccb24", sku: "DCCB24", name: "Dukers 24\" Radiant Broiler", cat: "roaster", art: "oven", price: 1100, images: ["/products/dccb24-1.jpg"], brand: "Dukers", rating: 4.6, n: 119, badge: "Sale", stock: "in", description: "24\" gas radiant broiler with cast-radiants for steady, high char-heat. CSA.", specs: { "Width": "24\"", "Depth": "28¾\"", "Height": "15⅜\"", "Weight": "132 lbs", "Gas Type": "Natural / LP", "Certification": "CSA" } }),

  // ---------- Electric & Automation ----------
  P({ slug: "57277", sku: "57277", name: "Automatic Intelligent Stir-Fry Machine — 2-Head", cat: "electric", art: "range", price: 20130, images: ["/products/57277-1.png"], brand: "Panda®", rating: 4.8, n: 18, badge: "New", stock: "in", description: "Commercial automatic stir-fry machine — cook expert-level dishes in ~3 minutes, one chef runs three units, saving 52–68% versus gas.", specs: { "Width": "65\"", "Depth": "46\"", "Height": "64\"", "Weight": "1,200 lbs", "Voltage": "208–240 V", "Power": "5 kW + 5 kW", "Phase": "Single", "Installation": "Mobile" } }),
  P({ slug: "52491", sku: "52491", name: "Auto-Lift Noodle Cooker — 3 Holes, Single Tank", cat: "electric", art: "range", price: 6420, images: ["/products/52491-1.png", "/products/52491-2.jpg"], brand: "Panda®", rating: 4.8, n: 44, stock: "in", description: "Electric auto-lift noodle cooker with three cooking holes, per-basket timers with memory and auto-refill sensor.", specs: { "Width": "13\"", "Depth": "32\"", "Height": "53\"", "Weight": "110 lbs", "Water Capacity": "6 gal", "Voltage": "208–240 V", "Power": "6 kW", "Holes": "3" } }),
  P({ slug: "ind-e120v", sku: "IND-E120V", name: "Adcraft Electric Induction Cooker — 120V", cat: "electric", art: "range", price: 525, images: ["/products/ind-e120v-1.jpg"], brand: "Adcraft", rating: 4.5, n: 263, stock: "in", description: "Heavy-duty stainless and ceramic-glass countertop induction cooker with self-check function — turn any surface into a stovetop.", specs: { "Voltage": "120V", "Material": "Stainless / ceramic glass", "Type": "Countertop induction", "Feature": "Self-check" } }),
  P({ slug: "21716", sku: "21716", name: "Peking Duck Oven — 208-240V / 12.8kW", cat: "electric", art: "oven", price: 18942, images: ["/products/21716-1.png"], brand: "Panda®", rating: 4.9, n: 24, stock: "back", description: "Electric Peking duck roaster with programmable recipe keypad, timer, humidify and smoke-elimination functions.", specs: { "Voltage": "208–240 V", "Power": "12.8 kW", "Control": "16-recipe keypad", "Feature": "Auto-clean, humidify", "Material": "Stainless" } }),

  // ---------- Small Appliances ----------
  P({ slug: "19974", sku: "19974", name: "Scallion Shredder", cat: "electric-kitchen-tool", art: "wok", price: 897, images: ["/products/19974-1.jpg"], brand: "Panda®", rating: 4.7, n: 156, stock: "in", description: "Portable electric scallion shredder — 2.2–9 mm blade, ~30 scallions/min, quiet 300W motor.", specs: { "Width": "17\"", "Depth": "9\"", "Height": "17\"", "Weight": "28 lbs", "Blade": "2.2–9 mm", "Power": "300W", "Voltage": "110–240V" } }),
  P({ slug: "22228", sku: "22228", name: "Scallion Slicer", cat: "electric-kitchen-tool", art: "wok", price: 897, images: ["/products/22228-1.jpg"], brand: "Panda®", rating: 4.7, n: 132, badge: "Sale", stock: "in", description: "Portable electric scallion slicer — 1–5 mm blade at 1,026 rpm for fine, consistent cuts.", specs: { "Width": "17\"", "Depth": "9\"", "Height": "13\"", "Weight": "13 lbs", "Blade": "1–5 mm", "Power": "150W", "Speed": "1,026 rpm" } }),
  P({ slug: "22230", sku: "22230", name: "Hot Pepper Slicer", cat: "electric-kitchen-tool", art: "wok", price: 897, images: ["/products/22230-1.jpg"], brand: "Panda®", rating: 4.6, n: 108, badge: "Sale", stock: "in", description: "Portable electric hot-pepper slicer — adjustable 1–7 mm blade at 280 rpm.", specs: { "Width": "15\"", "Depth": "9\"", "Height": "13\"", "Weight": "13 lbs", "Blade": "1–7 mm", "Power": "150W", "Speed": "280 rpm" } }),
  P({ slug: "rc-e50", sku: "RC-E50", name: "Adcraft 50-Cup Rice Cooker", cat: "electric-kitchen-tool", art: "rice", price: 625, images: ["/products/rc-e50-1.jpg"], brand: "Adcraft", rating: 4.6, n: 198, stock: "in", description: "Cook up to 50 cups of rice evenly and thoroughly — built for busy commercial kitchens.", specs: { "Capacity": "50 cups", "Type": "Rice cooker", "Brand": "Admiral Craft" } }),
  P({ slug: "allpoints8018182", sku: "HCU040S", name: "Hamilton Beach 40-Cup Stainless Coffee Urn", cat: "electric-kitchen-tool", art: "rice", price: 356, images: ["/products/allpoints8018182-1.jpg"], brand: "Hamilton Beach", rating: 4.6, n: 240, stock: "in", description: "Corrosion-free stainless coffee urn with quick-twist locking lid and one-hand dispensing. 40-cup capacity.", specs: { "Capacity": "40 cups", "Material": "Stainless", "Lid": "Quick-twist lock", "Power": "Electric" } }),
  P({ slug: "univexcorp-21", sku: "Sprizza 50", name: "Sprizza 50 Pizza Spinner", cat: "electric-kitchen-tool", art: "wok", price: 10001, images: ["/products/univexcorp-21-1.png"], brand: "Univex", rating: 4.5, n: 12, stock: "back", description: "Bench-model cold-system pizza dough spinner that reproduces the pizzaiolo's manual dexterity for perfectly formed bases.", specs: { "Type": "Dough spinner", "System": "Cold", "Model": "Bench" } }),

  // ---------- Refrigeration ----------
  P({ slug: "d47ef", sku: "D47EF", name: "Dukers Shallow-Depth 2-Door Reach-In Freezer", cat: "refrigeration", art: "fridge", price: 3572, images: ["/products/d47ef-1.png"], brand: "Dukers", rating: 4.7, n: 96, stock: "in", description: "Shallow-depth two-section reach-in freezer, 29.51 cu ft, digital control 0°F to -8°F, auto-defrost, R290, ETL-Sanitation.", specs: { "Width": "47¼\"", "Depth": "28\"", "Height": "79\"", "Capacity": "29.51 cu ft", "Temp": "0°F to -8°F", "Refrigerant": "R290", "Voltage": "115V", "Certification": "cETLus" } }),
  P({ slug: "dcb72-d4", sku: "DCB72-D4", name: "Dukers 72\" 4-Drawer Refrigerated Chef Base", cat: "refrigeration", art: "table", price: 3221, images: ["/products/dcb72-d4-1.jpg"], brand: "Dukers", rating: 4.7, n: 74, badge: "New", stock: "in", description: "72\" refrigerated chef base, four drawers (12 × 1/6 pans each), 33–38°F, 304 stainless, heavy-duty casters, R290.", specs: { "Width": "72\"", "Depth": "32¼\"", "Height": "25\"", "Weight": "308 lbs", "Temp": "33–38°F", "Drawers": "4", "Refrigerant": "R290", "Certification": "cETLus" } }),
  P({ slug: "dsp72-30m-d6", sku: "DSP72-30M-D6", name: "72\" Mega-Top Sandwich Prep Table — 6 Drawers", cat: "refrigeration", art: "table", price: 3980, images: ["/products/dsp72-30m-d6-1.png"], brand: "Dukers", rating: 4.8, n: 61, stock: "in", description: "Mega-top sandwich/salad prep table, 30 × 1/6 pans, six self-closing drawers, 34–47°F, R290, ETL-Sanitation.", specs: { "Width": "72½\"", "Depth": "31½\"", "Height": "45¾\"", "Capacity": "17.58 cu ft", "Temp": "34–47°F", "Pans": "30 × 1/6", "Refrigerant": "R290" } }),
  P({ slug: "dim-1050a", sku: "DIM-1050A", name: "Ice Maker w/ 550 lb Bin — 1,090 lb/24h", cat: "refrigeration", art: "fridge", price: 7425, images: ["/products/dim-1050a-1.jpg"], brand: "Dukers", rating: 4.7, n: 52, stock: "in", description: "Cube-style air-cooled ice maker, up to 1,090 lb/24h with a 550 lb storage bin, stainless exterior, R290.", specs: { "Production": "1,090 lb/24h", "Bin": "550 lb", "Type": "Cube, air-cooled", "Voltage": "230V", "Refrigerant": "R290", "Certification": "cETLus" } }),

  // ---------- Ventilation & Hoods ----------
  P({ slug: "bs-216q-72k", sku: "BS-216Q-72K", name: "Kitchen Ventilation & Purification System", cat: "hood", art: "lamp", price: 30000, images: ["/products/bs-216q-72k-1.jpg"], brand: "Panda®", rating: 4.8, n: 9, stock: "back", description: "High-capacity kitchen ventilation and purification system — 42,400 CFM rated airflow for heavy wok lines.", specs: { "Airflow": "42,403 CFM", "Flange": "1837 × 2295 mm", "Power": "5,880 W", "Dimensions": "2213 × 1470 × 2546 mm", "Weight": "1,152 kg" } }),
  P({ slug: "21528", sku: "21528", name: "Box Make-Up Air Canopy — 5' Depth", cat: "hood", art: "lamp", price: 292, images: ["/products/21528-1.jpg"], brand: "Panda®", rating: 4.5, n: 21, stock: "in", description: "Box make-up air canopy hood, 5' depth — balances exhaust with tempered replacement air.", specs: { "Depth": "5'", "Type": "Make-up air canopy" } }),

  // ---------- Accessories ----------
  P({ slug: "dcos-1874", sku: "DCOS-1874", name: "Dukers 72\" Stainless Overshelf", cat: "accessories", art: "rack", price: 472, images: ["/products/dcos-1874-1.jpg"], brand: "Dukers", rating: 4.7, n: 143, stock: "in", description: "72\" double stainless overshelf to add plating and landing space above prep lines. ETL.", specs: { "Width": "18\"", "Length": "73¾\"", "Height": "32\"", "Weight": "51 lbs", "Certification": "ETL" } }),
  P({ slug: "wl-66-st", sku: "WL-66-ST", name: "Winholt 6-Tier Steel Lockers — Slant Top", cat: "accessories", art: "rack", price: 947, images: ["/products/wl-66-st-1.jpg"], brand: "Winholt", rating: 4.6, n: 38, stock: "in", description: "One column of six locker compartments, slanted top, all-steel construction for staff areas.", specs: { "Tiers": "6", "Columns": "1", "Depth": "12\"", "Height": "78\"", "Material": "Steel" } }),
  P({ slug: "ug20-3v-u23-ucp", sku: "UG20-3V-U23", name: "Anets 20\" Triple Fryer w/ Filter Drawer — NG", cat: "accessories", art: "fryer", price: 55374, images: ["/products/ug20-3v-u23-ucp-1.png"], brand: "Anets", rating: 4.9, n: 7, stock: "back", description: "Gold/Platinum-series 20\" × 20\" triple fryer battery with built-in filter drawer and U23 controls. 225,000 BTU natural gas.", specs: { "Vats": "3", "Total BTU": "225,000", "Gas Type": "Natural", "Controls": "U23", "Feature": "Filter drawer" } }),

  // ---------- Kitchenware ----------
  P({ slug: "wdp011-102", sku: "WDP011-102", name: 'Winco 7½" Square Porcelain Plate (Case)', cat: "kitchenware", art: "wok", price: 71, images: ["/products/wdp011-102-1.jpg"], brand: "Winco", rating: 4.6, n: 88, stock: "in", description: "Durable porcelain square plate with medium rim for high-volume foodservice. Dishwasher safe. Sold by the case.", specs: { "Size": "7½\" square", "Rim": "Medium", "Material": "Porcelain", "Pack": "Case" } }),
  P({ slug: "spjp-102", sku: "SPJP-102", name: "Winco Full-Size Steam Table Pan — 23ga SS", cat: "kitchenware", art: "wok", price: 16, images: ["/products/spjp-102-1.jpg"], brand: "Winco", rating: 4.8, n: 312, stock: "in", description: "Full-size (1/1) anti-jamming steam table pan in 18/8 stainless, 23-gauge, 2½\" deep. NSF.", specs: { "Size": "Full-size (1/1)", "Depth": "2½\"", "Gauge": "23", "Material": "18/8 stainless", "NSF": "Yes" } }),
  P({ slug: "afp-12", sku: "AFP-12", name: 'Winco 12" Aluminum Fry Pan — Mirror Finish', cat: "kitchenware", art: "wok", price: 20, images: ["/products/afp-12-1.jpg"], brand: "Winco", rating: 4.7, n: 205, stock: "in", description: "Majestic 12\" round fry pan in 3.5 mm 3003 aluminum with riveted handle — excellent heat conductivity. NSF.", specs: { "Diameter": "12\"", "Thickness": "3.5 mm", "Material": "3003 aluminum", "Handle": "Riveted", "NSF": "Yes" } }),
  P({ slug: "cvld-13r", sku: "CVLD-13R", name: "Winco 1 oz Polycarbonate Ladle — Red", cat: "kitchenware", art: "wok", price: 1.61, images: ["/products/cvld-13r-1.jpg"], brand: "Winco", rating: 4.7, n: 421, stock: "in", description: "1 oz color-coded polycarbonate portion ladle, 13\" overall, ergonomic handle. NSF.", specs: { "Volume": "1 oz", "Length": "13\"", "Material": "Polycarbonate", "Color": "Red", "NSF": "Yes" } }),
];
